services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
        - .env
    ports:
      - "8000:8000"
    restart: always
